=== lobehub/lobe-vidol-market/schema/vidolDanceSchema_v1.json
{"type":"object","properties":{"danceId":{"type":"string"},"name":{"type":"string"},"src":{"type":"string"},"author":{"type":"string"},"homepage":{"type":"string"},"audio":{"type":"string"},"cover":{"type":"string"},"thumb":{"type":"string"},"readme":{"type":"string"},"createAt":{"type":"string"},"schemaVersion":{"type":"number"}},"required":["danceId","name","src","author","homepage","audio","cover","thumb","createAt","schemaVersion"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}

=== lobehub/lobe-vidol-market/src/dances/kara-lupin.json
{
  "danceId": "kara-lupin",
  "name": "Kara - LUPIN",
  "author": "rdmclin2",
  "homepage": "https://github.com/rdmclin2",
  "src": "https://r2.vidol.chat/files/2024/10/03/9e8f5506-513a-4453-8efd-7511c97b4fe2.vmd",
  "audio": "https://r2.vidol.chat/files/2024/10/03/76d1b86a-27d0-49f1-92fc-c68884c5087e.mp3",
  "cover": "https://r2.vidol.chat/files/2024/10/03/620db86e-57f6-4698-a899-4f8068ae8b22.webp",
  "thumb": "https://r2.vidol.chat/files/2024/10/03/f5385ccb-631f-4e44-a929-d8a1015f8dda.webp",
  "readme": "------------------------------------------\r\n KARA LUPIN (Short) MMD用モーションデータ\r\n------------------------------------------\r\n\r\n　ダウンロードありがとうございます。\r\n　改造・切り貼り大歓迎ですので色々いじって遊んで頂ければ嬉しいです。\r\n\r\n\r\n○内容のブツ\r\n\r\n　① lupin-モーション1.vmd　\r\n  ② lupin-モーション2(グネる用).vmd --- 足首が浮いてしまう場合にはコチラを使って下さい。\r\n　③ lupin-口パク.vmd --- 表情リップ△がある方がそれっぽくなります。\r\n　④ lupin-目線.vmd \r\n\r\n　・上半身2ボーン必須です。\r\n　・表情はついていません。口パク/目線もお好みで自由に組み合わせてお使い下さい。\r\n　・蹴りのモーションがいくつかありますが高確率でグネります。\r\n　・モデルによっては肩が破綻気味になったり手が体に埋まったりします。\r\n　　下半身のスッキリしたモデルだと逆に手がかなり浮いてしまうかもしれません。\r\n　　腰周りのパーンと張った女性体系モデルと相性がいいみたいです。\r\n\r\n　全体的に粗だらけで申し訳ないのですがカメラなんかで誤魔化して頂ければと思います。\r\n\r\n○モーショントレス元\r\n\r\n　YouTube 　　 (高音質)KARA-Lupin 日本語Ver\r\n　ニコニコ動画　sm14566712 / sm9871448\r\n\r\n　・原曲フルサイズではなくサビ1回目までくらいの長さに省略しています。\r\n　・振り付けの順序を変えていたり、トレス対象が動画を跨いで混ざっていたり、\r\n　　間を適当に繋いだモーションが入っていたりします。\r\n  ・使用曲タイトル・アーティスト名に関して、私は極度のビビリなので検索避けしていますが\r\n　　もしも投稿などに利用する際は各個人のご判断にお任せしたいと思います。\r\n　・各方面にご迷惑にならない利用の仕方をお願い致します。\r\n　・このデータを利用した事で発生した如何なる問題に対しても責任は負いかねますのでご了承下さい。\r\n\r\n○お借りしたもの\r\n\r\n　ソフト　MikuMikuDance_v739dot / Face And Lips V0.3.8.1　\r\n  モデル　TETA様　かすが＠戦国BASARA1.2 --- モーショ",
  "schemaVersion": 1,
  "createAt": "2024-10-03"
}
